// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vjdprmksxsckfufjyqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqZHBybWtzeHNja2Z1Zmp5cXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDc0MDMsImV4cCI6MjA2NTQ4MzQwM30.ciiWK8EGGsR6O632U_EyypaiFVEAg-f2SJN1s0Av_I8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);